require 'jade/frontend/pattern_analysis/pattern'
require 'jade/frontend/pattern_analysis/signature'
require 'jade/frontend/pattern_analysis/matrix'
require 'jade/frontend/pattern_analysis/witnesses'
require 'jade/frontend/pattern_analysis/exhaustiveness'
